import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Admin Page clone",
  description: "Generated by next",
};

export default function RootLayout({ children, }: 
  Readonly<{children: React.ReactNode}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
